#!/usr/bin/env bash
# Configure your Nginx server so that /
# redirect_me is redirecting to another page.
findThis="^\tlocation / {"
replaceThis="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
# redirect
findThis="^\tlocation / {"
replaceThis="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$findThis@$replaceThis@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
