#!/usr/bin/env bash
# Configure your Nginx server so that /
# redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
