#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
mysqldump --all-databases -p$1 -u root > backup.sql
format=$(date '+%d-%m-%Y')
tar -czvf $format.tar.gz backup.sql
