#!/usr/bin/env bash
# Configure domain zone so that the subdomain www
if [ $# -eq 1 ]; then
    sub_dom="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    sub_dom="$2.$1"
fi

dig $sub_dom | awk '/ANSWER SECTION:/{getline; split($1,b,"."); print "The subdomain", b[1], "is a", $4, "record and points to", $5}'
