#!/usr/bin/env bash
# Configure domain zone so that the subdomain www
# points to your load-balancer IP
show_subD () {
    record_new_ip=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk  '{ print $4,$5 }')
    record=$(echo $record_new_ip | awk '{ print $1 }')
    new_ip=$(echo $record_new_ip | awk ' { print $2 }')
    echo "The subdomain $2 is a $record and points to $new_ip"
}

if [ $# -eq 2 ]
then
    show_subD $1 $2
elif [ $# -eq 1 ]
then
    show_subD $1 www
    show_subD $1 lb-01
    show_subD $1 web-01
    show_subD $1 web-02
fi
