#!/usr/bin/env bash
# Configure domain zone so that the subdomain www
# points to your load-balancer IP
show_subD () {
    record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $4 }')
    new_ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $5 }')
}

if [ $# -eq 2 ]
then
    show_subD "$1" "$2"
elif [ $# -eq 1 ]
then
    show_subD "$1" "www"
    show_subD "$1" "lb-01"
    show_subD "$1" "web-01"
    show_subD "$1" "web-02"
fi
