#!/usr/bin/env bash
#Display numbers 1-100
#Display "FizzBuzz" on multiples of 3 & 5
#Display "Fizz" when number is mutiple of 3
#Display "Buzz" on multiples of 5
#if none of the above, display number
for (( i = 1; i < 100; i++ )); do
    if [ $((i % 3)) -eq 0] && [ $((i % 5)) -eq 0]
    then
	echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0]
    then
	 echo "Fizz"
