#!/usr/bin/env bash
# Script that prints "Holberton School" 10 times
# 9th line should  "Holberton School" new line "Hi"
i=1
while [ $i -lt 9 ]
do
    echo "Holberton School"
    i=$(($i + 1 ))
    if [[ $i -eq 9 ]];then
	echo "Holberton School" 
	echo "Hi"
    fi
    if  [[ $i -ge 9 ]];then
	echo "Holberton School"
    fi
done
