#!/usr/bin/env bash
# Print "Holberton School" on 8 lines
# Print bad luck on line 4
# Print good luck on 8th line
i=0
while [ $i -lt 10 ]
do
    (( i ++ ))
    if [[ $i -eq 4 ]]; then
	echo "bad luck"
	elif [ $i -eq 8 ];then
	echo "good luck"
    else
	echo "Holberton School"
    fi
done
