#!/usr/bin/env bash
# Print "Holberton School" on 8 lines
# Print bad luck on line 4
# Print good luck on 8th line
i=1
while [ $i -le 10 ] || [ $i -ne 4 ] || [ $i -ne 8 ]
do
    echo "Holberton School"
    (( $i + 1 ))
    if [[ $i -eq 4 ]]; then
	echo "bad luck"
    fi
    if [[ $i -eq 8]]; then
	echo "good luck"
    fi
done
