#!/usr/bin/env bash
#Print numbers 1-20
#4 displays "bad luck from China"
#9 displays "bad luck from Japan"
#17 displays "bad luck from Italy"
i=1
while [ $i -le 20 ]
do
    echo "$i"
    i=$(( $i + 1 ))
    case $i in
	5)
	    echo "bad luck from China"
	    ;;
	10)
	    echo "bad luck from Japan"
	    ;;
	18)
	    echo "bad luck from Italy"
	    ;;
    esac
done
