#!/usr/bin/env bash
#Displaying hours 0-12 and minutes 1-59 for each hour

h=0
m=1

while [ $h -lt 13 ]
do
	echo "Hour: $h"
	while [ $m -lt 60 ]
	do
	    echo $m
	    m=$((m+1))
	done
	m=1
	h=$(( h + 1 ))
done
