#!/usr/bin/env bash
#Gives info about file "holbertonschool"
#Using if and else
h="holbertonschool"
if [ -e "$h" ]
then
    echo "holbertonschool file exists"
    if [ -s "$h" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$h" ]
    then
	echo "holbertonschool file is a regular file"
    fi
    else
    echo "holbertonschool file does not exist"
fi
