#!/usr/bin/env bash
# Configure Nginx per task 0
findThis="^\tlocation / {"
new301="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
new404="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By $HOSTNAME;\n\n\tlocation / {"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "s@$findThis@$new301@" /etc/nginx/sites-available/default
sudo sed -i "s@$findThis@$new404@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
